### PR TITLE
Badges and buttons

### PR DESCRIPTION
**Pull request by rahulk31**
Since both were small components so have committed in same branch. Although both components has been committed separately for easier review. Kindly provide suggestions to improve.

### CODE REVIEW

**Review by Naman-Saxena1 — CHANGES_REQUESTED** [review]
You should add Icon Buttons and Link Buttons as per LMS PRD. 
While development, make sure you are making everything from PRD Checklist.

For Commit messages, try using pre-fixes like feat, style as best practice.
https://neog.camp/guide/lesson-two#ex05---understanding-commit-messages

Code looks fine. 👍

**Comment by mehulsatardekar** [comment]
you have nicely named CSS classes and code is clean , From my side good to merge @rahulk31

**Comment by rahulk31** [comment]
> You should add Icon Buttons and Link Buttons as per LMS PRD. While development, make sure you are making everything from PRD Checklist.
> 
> For Commit messages, try using pre-fixes like feat, style as best practice. https://neog.camp/guide/lesson-two#ex05---understanding-commit-messages
> 
> Code looks fine. 👍

Thanks @Naman-Saxena1 for these pointers, really helpful. As suggested, I have added link and icon buttons, also improved my commit message. 😃

**Comment by rahulk31** [comment]
> you have nicely named CSS classes and code is clean , From my side good to merge @rahulk31

Thank you @mehulsatardekar for the review. 😃

**Pull request merged**
