### PR TITLE
:tada: created landing page and layout for documentation

### PR DESCRIPTION
**Pull request by rahulk31**

### CODE REVIEW

**Comment by rahulyadav139** [comment]
Files are readable, class names are quite simple but classes are extensive. Docsite layout is looking great. It seems styles are not applied on the buttons on the homepage, I don't know the actual cause but look into it. Overall aesthetically the website is pleaseing. Great work.

**Comment by rahulk31** [comment]
> 

Thanks @rahulyadav139 for the review. Yeah the buttons style will be applied after I add the buttons component. At the moment it is not present.

**Review by dev-prabhat — APPROVED** [review]
Good to merge just add some style to Call to Action Buttons

**Comment by rahulk31** [comment]
> Good to merge just add some style to Call to Action Buttons

Sure Prabhat, thank you for the review.

**Pull request merged**
